### ISSUE TITLE
 pygmentize: command not found 

### ISSUE THREAD

**Issue by popey** [Henryws/pacstall#17]
**Describe the bug**

The installer appears to be missing pygmentize as a dependency

**To Reproduce**

1. `sudo bash -c "$(curl -fsSL https://git.io/JfHDM)" `
2. `pacstall -U`
3. `pacstall -S neofetch`
Here's the output:

```bash
alan@thinkpad-x220:~$ pacstall -U 
Are you sure you want to update pacstall? [Y/n] y 
  ____                  __        ____ 
 / __ \____ ___________/ /_____ _/ / / 
/ /_/ / __ `/ ___/ ___/ __/ __ `/ / / 
/ ____/ /_/ / /__(__  ) /_/ /_/ / / / 
/_/    \__,_/\___/____/\__/\__,_/_/_/ 

[+] INFO: You are at version 1.1 Onyx 
alan@thinkpad-x220:~$ pacstall -S neofetch
neofetch is available. Do you want to view the pacscript [Y/n] y
/usr/share/pacstall/scripts/search.sh: line 14: pygmentize: command not found
alan@thinkpad-x220:~$    
```

**Expected behavior**

Show search results for looking for `neofetch`

**Screenshots**

![image](https://user-images.githubusercontent.com/1841272/116982865-43238900-acc1-11eb-9d82-29e438f1ffec.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04 under WSL
- Version (I assume this means version of pacstall?) 1.1

**Comment by Henryws** [comment]
Ah, forgot to add pygmentize to to installer, give me a second

**Comment by Henryws** [comment]
When you  ran the installer, it should have installed python3-pygments right?

**Comment by popey** [comment]
That was indeed installed.

**Comment by Henryws** [comment]
Then it must be under a different binary then on Linux Mint, I'll do some digging

**Comment by popey** [comment]
It's in python-pygments, not python3-pygments. https://packages.ubuntu.com/search?searchon=contents&keywords=pygmentize&mode=exactfilename&suite=bionic&arch=any

**Comment by Henryws** [comment]
Yeah that should be it, Linux Mint just has different names, I'll update the script
