### ISSUE TITLE
Flags are a little at odds with pacman

### ISSUE THREAD

**Issue by mfdorst** [Henryws/pacstall#18]
**Is your feature request related to a problem? Please describe.**

It's a little odd to have a `-S` flag which does something different from what it does in `pacman`. I suspect that a lot of people will expect `-S` to install programs, rather than search for them.

**Describe the solution you'd like**

I think that either of two approaches to the flag names would make more sense:

1. Emulate the behavior of pacman (similar to `yay` and `paru`)
2. Use a completely different set of flags, e.g.
    + `pacstall -i` for install, `pacstall -s` for search, or
    + `pacstall install` where you can shorten it to `pacstall i` (this would be reminiscent of tools like `npm` and `cargo`).

In order to not break backward compatibility, you could just mark the current flags as deprecated, so they would remain operational, but the documentation would show the less confusing flags.

**Comment by mfdorst** [comment]
Obviously if you took approach 1 there would be no way to maintain backward compatibility though. But I suspect that since you don't have a huge user base just yet, that would probably be okay.

**Comment by mfdorst** [comment]
Btw I think this project is really cool and I hope to see it grow a lot. Great work.

**Comment by Henryws** [comment]
To be fair Ubuntu users won't really get Pacman flags and they are kind of intuitive so I don't think there's a need to switch up the flags

**Comment by mfdorst** [comment]
That may be true in the long run, but I suspect that most people who would be interested in this project, especially in the short term, are people who are familiar with arch and the AUR, and wish there was an equivalent for Debian/Ubuntu (like me).

**Comment by Henryws** [comment]
What I could do is make it so pacstall be able to emulate apt commands like install, remove, upgrade, etc

**Comment by Henryws** [comment]
I think people can switch one flag in the command there running. It's annoying, but that's just how I made it

**Comment by Arsen6331** [comment]
If you really want to use different flags, just use a wrapper. It's really not that hard to make a simple script to translate the flags.
