### ISSUE TITLE
Would you consider using python?

### ISSUE THREAD

**Issue by mfdorst** [Henryws/pacstall#19]
**Is your feature request related to a problem? Please describe.**

I think bash scripting will quickly start to feel a little unmanageable if this project grows large, which I really hope it does.

**Describe the solution you'd like**

I think that writing some of the bigger scripts in Python would provide a lot of benefits.

+ People tend to prefer writing Python to Bash (at least in my experience) so you'll get more help from the community
+ Python has a huge amount of tooling just in its built in libraries (`argparse` for instance makes argument parsing a breeze)
+ Python code is a lot easier to write tests for than bash scripts

**Describe alternatives you've considered**

There are lots of other languages that could be used, like Ruby which is also great for this kind of thing, but it is not installed by default on Ubuntu.

**Comment by Henryws** [comment]
Well makepkg is actually a bash script. And I am not that good at python. I've considered it but it's to much hastle

**Comment by mfdorst** [comment]
Oh wow, I wasn't aware of that. That seems insane to me.

**Comment by mfdorst** [comment]
Oh well on second thought, I guess they don't have much choice, because they can't have a dependency like python, so for them it would probably be a choice between C and bash.

**Comment by Arsen6331** [comment]
> Oh well on second thought, I guess they don't have much choice, because they can't have a dependency like python, so for them it would probably be a choice between C and bash.

The choice is not between C and Bash. It's between the many, many compiled languages and Bash. The reason it's a bash script is that PKGBUILDs themselves are bash scripts, so using bash is the easiest way to go about parsing them.
