### ISSUE TITLE
Validation of checksums (e.g. SHA, MD5)

### ISSUE THREAD

**Issue by ReneganRonin** [Henryws/pacstall#20]
I noticed that pacstall does not have a way of checking package sums and integrity, is this feature planned? It would be great feature to add it so that users can know that the package they have downloaded and installed is correct. Please do correct me if I missed something.

**Comment by Henryws** [comment]
It does. look at one of the packages at [pacstall-packages](https://github.com/Henryws/pacstall-packages). It works on everything except git clones, b/c I think it does that automatically and if it doesn't, I've never seen a broken git repo before. One note is that if you don't include an sha256sum, pacstall just goes over it and accepts it as validated
