### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SomethingGeneric** [Henryws/pacstall#21]
If there's a separate repo for packages, what purpose does the `packages/` subfolder in this repo serve?

**Comment by SomethingGeneric** [comment]
The main reason that I ask is because I'd like to help write pacscripts and I'd love to not waste any time putting them in the wrong place :)

**Comment by Henryws** [comment]
Yeah, good question. the packages directory here is for me personally and you shouldn't install from here. At [pacstall-programs](https://github.com/Henryws/pacstall-programs) is where the packages that users install
