### ISSUE TITLE
[ Suggestion ] change the options

### ISSUE THREAD

**Issue by mrbooshehri** [Henryws/pacstall#29]
First of all thank you for starting a cool project and I hope it progresses quickly.
As far as most of the Ubuntu (also other Debain-based) users utilize ```apt-get```  and  ```apt```  as their package manager, they're familiar with options that exist in the mentioned package mangers ( like ``` install, remove``` ) . So I think it would be a better idea to follow that structure to make ease of use.

**Comment by Henryws** [comment]
I do have flags for that! Run `pacstall --help` to see shorthand and fullhand flags
