### ISSUE TITLE
pygmentize not found when doing -S

### ISSUE THREAD

**Issue by louis77** [Henryws/pacstall#31]
**Describe the bug**
On a clean Ubuntu 20.04 LTS install when I try to **search** for `neofetch` I get this:

```
louis@ubuntu:/usr/share/pacstall$ sudo pacstall -S neofetch
neofetch is available. Do you want to view the pacscript [Y/n] Y
/usr/share/pacstall/scripts/search.sh: line 14: pygmentize: command not found
```

With normal -I install it works.

**Desktop (please complete the following information):**

- OS + version: Ubuntu 20.04
- Pacstall Version: 1.1 Onyx

**Comment by Henryws** [comment]
Install `python-pygments`

**Comment by louis77** [comment]
It is already there:

```
$ sudo apt install python-pygments
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pygments is already the newest version (2.3.1+dfsg-1ubuntu2.2).
0 upgraded, 0 newly installed, 0 to remove and 107 not upgraded.

```

**Comment by Henryws** [comment]
`python3-pygments`

**Comment by Henryws** [comment]
I’m probably going to remove pygments from the code because it’s causing a lot of problems

**Comment by Henryws** [comment]
Done. Pygments is completely removed
