### ISSUE TITLE
Better handle conflicting packages

### ISSUE THREAD

**Issue by wizard-28** [Henryws/pacstall#32]
**Is your feature request related to a problem? Please describe.**
1. Currently `pacstall` checks only for conflicting packages installed by it, but what happens when the user has installed the same package from the official repos? In that case the install would break.
2. Currently `pacstall` just exits out of the installation process if it detects conflicting packages.

**Describe the solution you'd like**
1. Query `apt` or `dpkg` for conflicting packages too.
2. Offer a confirmation to the user to uninstall the conflicting packages when a conflicting package is detected.

**Describe alternatives you've considered**
None. What do you think?

**Additional context**
None

**Comment by Henryws** [comment]
If a package (say neofetch) is installed with apt, stow will error out saying existing files are in place on the system and pacstall will quit. Is that what you want or do you want the option to remove the apt one?

**Comment by wizard-28** [comment]
Remove the apt one as per the second request mentioned

**Comment by Henryws** [comment]
I’ll work on that later

**Comment by wizard-28** [comment]
@Henryws  Should package maintainers put the package name in the `breaks` variable, like that it would check if the package is already installed from `apt`. Or should they just leave it empty (or add other things)

**Comment by Henryws** [comment]
They should put something for break if it’s something like foo-git conflicts with foo
