### ISSUE TITLE
Provide IRC channel

### ISSUE THREAD

**Issue by ifrendas** [Henryws/pacstall#37]
**Is your feature request related to a problem? Please describe.**
Currently a Discord chat is provided for the project. Discord is a [proprietary](https://spyware.neocities.org/articles/discord.html) [mess](https://stallman.org/discord.html) which I'd like to avoid.

**Describe the solution you'd like**
An IRC channel could be created on [Freenode](https://freenode.net/).

**Comment by Henryws** [comment]
I'm not so good with IRC and Discord is easier and the majority of people wanting help will be put off by the fact we would be using archaic means. So no, no IRC
