### ISSUE TITLE
Dependencies not installed automatically or README doesn't guide to install them

### ISSUE THREAD

**Issue by hellaguy** [Henryws/pacstall#38]
**Describe the bug**
[Distrotube](https://www.distrotube.com/) recently did [a video](https://odysee.com/@DistroTube:2/pacstall-is-an-aur-for-ubuntu:8) on pacstall. He had issues with dependencies not being installed (such as stow, python3-pygments; additionally in case of vim it doesn't install libncurses-dev)

**To Reproduce**

1. Install pacstall as usual on a new Ubuntu install
2. Search and choose to view the pacstall script

For the vim error try to install vim and it will show the error.

Please look in the video for details.

**Expected behavior**

Should install the dependencies automatically when installing pacstall or vim.

If pacstall deps are not possible to be installed automatically, there should be a mention to install them on README.md

**Screenshots**

**Desktop (please complete the following information):**

- OS + version: Ubuntu 21.04
- Pacstall Version: latest

**Additional context**
N/A

**Comment by Henryws** [comment]
Fixed
