### ISSUE TITLE
Why can't we use existing Arch/AUR Packages Repo?

### ISSUE THREAD

**Issue by iamtalhaasghar** [Henryws/pacstall#39]
**Is your feature request related to a problem? Please describe.**
This issue is more a sort of discussion on how we should create and ship packages to be used with pacstall. Clearly we have these approaches:
1. Use existing aur/arch packages
2. Create a new package base as we are doing right now
3. Maybe use both .i.e. Our new package base and existing arch repo
<br>

**Describe the solution you'd like**
I want to have existing arch/aur packages be installed with pacstall because there is already a great effort taken to create and manage arch packages and wiki. Why do the hardwork of creating new package base again?
<br>

**Describe alternatives you've considered**
Not sure, if this question is relevant.
<br>

**Additional context**
I use both arch based and ubuntu based distros and I don't know how programs are packaged in both distros. So, i don't know how this can be achieved. But it's linux man not _windoze_ so i believe we can sort this out.

**Comment by Henryws** [comment]
You could, but package names and variables are completely different so you _could_, but I don't personally

**Comment by iamtalhaasghar** [comment]
I totally respect your decision. For the sake of understanding, can you give us some more explanation?

**Comment by Henryws** [comment]
Arch and Ubuntu have totally different package names (can't give example but just try to make a pacscript with arch package names). You would obviously have to adapt those.

Second is variables. PKGBUILD's usually have arrays while pacscripts have variables; no biggie to change

Third is the way the two are built. Pacstall uses many different tools to install/remove/search packages. The most common one is `/usr/src/pacstall/pkg`, where all packages are required to install to so stow can symlink them to the system. 

So in all, you can and could adapt PKGBUILD's, but for me, it's to much work. You can do it if you want, but there are some things that need to be changed

**Comment by Henryws** [comment]
Does that help?

**Comment by iamtalhaasghar** [comment]
Yeah, thank you.
