### ISSUE TITLE
Change CI to a more updated one

### ISSUE THREAD

**Issue by wizard-28** [Henryws/pacstall#44]
**Is your feature request related to a problem? Please describe.**
Hound's shell linter (`Shellcheck`) is quite old `0.5.0`. So its not quite effective.

**Describe the solution you'd like**
Can we switch to another CI like [`CodeFactor`](https://www.codefactor.io/), [`Codacy`](https://www.codacy.com/) or [`Codeclimate`](https://codeclimate.com/), since they provide up-to-date linters for shell scripts?

**Describe alternatives you've considered**
None.

**Additional context**
Latest `Shellcheck` version is `0.7.2`

**Comment by Henryws** [comment]
Hound is more of a tester. @louis77 made a custom tester by himself so we could use any of the ones you provided

**Comment by wizard-28** [comment]
Okay, I recommend CodeFactor or Codacy, I think CodeClimate is paid.

**Comment by Henryws** [comment]
![image](https://user-images.githubusercontent.com/58742515/117536501-ee358a80-afc0-11eb-8a36-9e076cd49275.png)

**Comment by wizard-28** [comment]
Did you configure it?
Add the pull request hook too, for auto pull request checking just like hound

**Comment by Henryws** [comment]
Sorry, typo. How would I do that?

**Comment by wizard-28** [comment]
Ahh... click on the hamburger menu (3 lines on top right corner) and click settings
