### ISSUE TITLE
`pacstall -R <program>` is not removing dependencies

### ISSUE THREAD

**Issue by wizard-28** [Henryws/pacstall#45]
**Describe the bug**
`pacstall -R <program>` is not removing either the `pacstall` or `apt` dependencies

**To Reproduce**
1. Just try to remove any program installed by pacstall which has dependencies.
2. After the program is uninstalled try running any of the programs installed by pacstall as a dependency
3. See that the program is executing and still present in your system (which it should not be)

**Expected Behaviour**
`pacstall` should remove all the dependencies when a program is uninstalled (both `apt` and `pacstall`), excluding common dependencies used by multiple programs

**Screenshots**
None.

**Desktop (please complete the following information):**

- OS: Pop_OS
- Pacstall Version: 1.1 Onyx (latest version using `pacstall -U`)

**Additional context**
None

**Comment by Henryws** [comment]
I'll work on that later

**Comment by kaistian** [comment]
> pacstall should remove all the dependencies when a program is uninstalled (both apt and pacstall), excluding common dependencies used by multiple programs
pacstall shouldn't remove packages from apt automatically, since it actually doesn't know if it can.
Lets say packstall program A is depended on apt package B so pacstall install B.
The user later learn about B and uses B all the time, maybe have script or other packages not installed with apt that dependens on B.
The user doesn't use A anymore so it uninstall A, and if pacstall then uninstall B also it will potentially break a lot of things.

**Comment by wizard-28** [comment]
@kaistian True... But then hundreds of dependencies are orphaned. Maybe pacsctall should just warn the user to uninstall the dependencies themselves as they see fit?

**Comment by kaistian** [comment]
Yes, the only way to do this is to inform the user so the user can make a decision.

That is what apt does, when packages that is installed as a dependency and no other packages depends on them you get the message `The following packages were automatically installed and are no longer required:` and a list of packages names.

With apt the user can remove them with `apt-get autoremove`, it there are a package the user need the user need to run `apt-mark manual <package>` or `apt-get install <package>` to mark it as a manual installed package and not an automatically installed package. And the autoremove won't remove the package.

As a side note, `apt-mark showauto` list packages that is automatically installed aka dependencies and `apt-mark showmanual`list packages that is installed.

**Comment by Henryws** [comment]
Pacstall now tells the user what dependencies it installed when they are uninstalling
