### ISSUE TITLE
Unnecessary output possible inactive code

### ISSUE THREAD

**Issue by kaistian** [Henryws/pacstall#46]
This line always print out count since grep has `-c`, I guess it should be `-q` for quite?
https://github.com/Henryws/pacstall/blob/166e40be9847fa3690d2098e5b82cc2a6cdc4b38/misc/scripts/install-local.sh#L65

I'm not sure I understand this part, `replace` is a variable that is never set so this if statement is always true
https://github.com/Henryws/pacstall/blob/166e40be9847fa3690d2098e5b82cc2a6cdc4b38/misc/scripts/install-local.sh#L64
My guess is replace is something we can use in pacscript so this code should have a not `if [[ ! -z $replace ]]` ?

**Comment by Henryws** [comment]
I'll fix the first part, thanks, but the second is checking if the pacscript has a replace variable

**Comment by kaistian** [comment]
The if only runs when the replace variable is empty, we need the opposite logic, run when not empty so it can remove the package.
`-z, the length of STRING is zero` or are I'm missing something.

**Comment by Henryws** [comment]
Thanks, fixed it in master and develop branch
