### ISSUE TITLE
multiple download urls required.

### ISSUE THREAD

**Issue by kwon37xi** [Henryws/pacstall#50]
Sometimes one package requires multiple sources to be built.

AUR supports multiple sources and hashes like the following. https://aur.archlinux.org/packages/grive/
```
source=("${pkgname}-${pkgver}.tar.gz"::"https://github.com/vitalif/grive2/archive/v${pkgver}.tar.gz"
	"binutils_compilation.patch"::"https://github.com/vitalif/grive2/commit/b4d6ac055f8f16ac735a70036243bc4ea2334039.patch")
sha512sums=('609837fc93ad78d143dcb4d1f558743d413c887fec2e9aaac81edd58549b812db859aab5ce7f664f06564779cff4bae32d43529e47fcc36640f1a9b52c5b5888'
            'b425c524b28a3e245a4de6090b052a2b1e08a06b5b8227450f91a127d4ea67cc8b1f3a74ac802f1525126d236fa1ad2de0a171ef0fa241ad27b1164606ec0501')
```

Is this possible to support multiple urls and hashes?

If this possible, I'd like to port the AUR grive to pacstall.

**Comment by Henryws** [comment]
I'll try that when done with school

**Comment by Henryws** [comment]
I added a patching system. Look [here](https://github.com/Henryws/pacstall-programs/blob/master/make-a-pacscript.md) for more info. Hope this helps
