### ISSUE TITLE
[Bug] `Pacstall` is reading the file name of the `pacscript` and using it as the name of the directory when installing the package.

### ISSUE THREAD

**Issue by wizard-28** [Henryws/pacstall#55]
**Describe the bug**
`Pacstall` is reading the file name of the `pacscript` and using it as the name of the directory when installing the package.

**To Reproduce**
1. Install a package from pacstall
2. Do an `ls /usr/src/pacstall`
3. See that the package directory name is the name of the `.pacscript` file not the `name` variable inside the pacscript.

**Expected behavior**
Read the name of the directory it should install the package to from the pacscript's `name` variable. By doing this the developers can dynamically modify the name of the pacscript according to user choice.

For example, currently I am making an `emacs-git` pacscript, in there I have given the user the choice to install emacs as a CLI tool not the GUI one. If the user accepts the offer then it would install the package as `emacs-nox-git` (which is the official name of emacs without GUI) if not then it would install it as `emacs-git`. Right now I can't do this as `pacstall` is not using the `name` variable for package directory naming.

**Screenshots**
None

**Desktop (please complete the following information):**

- OS: Pop!_OS 20.04
- Pacstall Version: latest

**Additional context**
Nope

**Comment by Henryws** [comment]
That would overwrite the files from `emacs`

**Comment by Henryws** [comment]
I don't think messing with the name variable is the best idea

**Comment by wizard-28** [comment]
AUR scripts do that, they mess with everything from what I can see xD

**Comment by wizard-28** [comment]
> That would overwrite the files from `emacs`

No it wont, the name would be either `emacs-git` or `emacs-nox-git` not `emacs` for this particular pacscript

**Comment by Henryws** [comment]
Would that be confusing for the user unless you explain it

**Comment by wizard-28** [comment]
Well, the `emacs-git` package REQUIRES the user to edit they pacscript before running to enable certain preferences (usually by assigning "YES" to some parameters in the pacscript), and the pacscript STRONGLY ADVICES the users to read and understand the options in it, as it currently installs a highly opinionated version of emacs, so if they want to make emacs their own they gotta change the parameters.

So when they open the file they can see the name change.

Or, now that I think about it while writing lets just remove the name changes, its complicating things
