### ISSUE TITLE
[Meta] Add an auto-labeling bot 

### ISSUE THREAD

**Issue by wizard-28** [Henryws/pacstall#56]
**Is your feature request related to a problem? Please describe.**
Currently issues have to be labeled manually by @Henryws. This process can be automated using a labeling bot.

**Describe the solution you'd like**
I recommend using [issue-label-bot](https://github.com/marketplace/issue-label-bot) from the GitHub marketplace as it uses machine learning to classify issues, and you can customize it to your liking.

**Describe alternatives you've considered**
Use any other auto labeling solution, but I recommend the above bot.

**Additional context**
None.

**Comment by Henryws** [comment]
Done
