### ISSUE TITLE
Add a `pkgver()` function to automate `-git` pacscript updates

### ISSUE THREAD

**Issue by wizard-28** [Henryws/pacstall#59]
**Is your feature request related to a problem? Please describe.**
Currently people have to manually change the `version` variable when there is a new commit in the git repo of the pacscript they are maintaining.

**Describe the solution you'd like**
Make a `pkgver()` fuction that automates the updating of the pacscripts.
 
**Describe alternatives you've considered**
Come up with some other way to automate `-git` pacscript updates.

**Additional context**
We can get the latest SHA checksum of the remote git repo commit by using
```bash
git ls-remote https://github.com/${:owner}/${:repo} master | sed "s/refs\/heads\/.*//"
```
So we can compare the local commit SHA with the remote commit SHA maybe? Or come up with some other way of utilizing this remote SHA?

**Comment by Henryws** [comment]
How would the `version_gt` function figure out that it is a newer commit?

**Comment by Henryws** [comment]
And on top of that, this would mean that pacstall needs to remotely source a package to run the `pkgver` function, meaning less security

**Comment by wizard-28** [comment]
Well, since the user has already installed the `pacscript` in their system, the question of security doesn't arise as the user already has implicitly trusted the source. So I think its fine to source the remote `pacscript`

**Comment by Henryws** [comment]
But all the malicious AUR packages were modified after being fine

**Comment by Henryws** [comment]
I'll try working on it

**Comment by wizard-28** [comment]
> How would the `version_gt` function figure out that it is a newer commit?

We could make pacstall store the local version (Check if the `pkgver` function is present and use its output as the local version) and when checking for updates again run the local `pkgver` function of the pacscript (it would return an updated value this time using `git ls-remote https://github.com/${:owner}/${:repo} master | sed "s/refs\/heads\/.*//"`) so there is no need to query the remote pacscript, all update checking can be done locally!

**Comment by Henryws** [comment]
But running a local git-ls would output the same thing as running it when updating

**Comment by Henryws** [comment]
Nevermind, I get what you mean

**Comment by wizard-28** [comment]
No when looking for the local version we will check for the **stored** version (in `/var/log/pacstall_installed/<pkg>`), and when checking for updated version we will run the `pkgver()` (maybe store the copy of the function in `/var/log/pacstall_installed/<pkg>`), so it would return a new version

**Comment by Henryws** [comment]
Will pacstall just assume that any package ending with `-git` should use `pkgver`

**Comment by wizard-28** [comment]
Its a valid assumption but, I think it should manually check if that function exists. 

If that's not possible at the moment then it should assume that `-git` `pacscripts` use `pkgver()`

**Comment by Henryws** [comment]
Should I make a function that pacscripts can call on to get the Sha instead of the more complicated line?

**Comment by wizard-28** [comment]
Hmm... `git ls-remote https://github.com/${:owner}/${:repo} master | sed "s/refs\/heads\/.*//"` isn't that complicated really and this is my way of doing it, other maintainers can come up with their own methods in the future (like if `pacstall` supports `SVG`, `HG` (other VCSes) in the future), so they can use their own way of finding the latest commit/version

So I think we should let the maintainers handle it, like the KISS philosophy

**Comment by Henryws** [comment]
I'll add it but it can be optional for those who know what their doing

**Comment by wizard-28** [comment]
Okay, make sure to explain it in the `make-a-pacscript.md` file

**Comment by Henryws** [comment]
So I think I've got it*
In `upgrade.sh`, I replaced `remotever` with 
```bash
source <(curl -s "$REPO"/packages/"$i"/"$i".pacscript) && type pkgver &>/dev/null && pkgver || echo $version
``` 
which should source the remote script, check if `pkgver` exists, run it, or if not, echo `version`.

In `install-local.sh`, I put 
```bash
type -t pkgver > /dev/null 2>&1
if [[ $? -eq 0 ]] ; then
    pkgver
fi
```

**Comment by wizard-28** [comment]
Does it work?

**Comment by Henryws** [comment]
I don't know yet, I'm testing, just wanted to let you know

**Comment by Henryws** [comment]
On this repo I forked: https://github.com/Henryws/conky-manager2, I changed a file and it's not changing the output of `git ls-remote https://github.com/Henryws/conky-manager2 master | sed "s/refs\/heads\/.*//"`

**Comment by wizard-28** [comment]
It would not change as there is no changes on the "master" branch change this `git ls-remote https://github.com/Henryws/conky-manager2 <branch> | sed "s/refs\/heads\/.*//"` with `add-1.10-support`

Basically what I am trying to say is that one has to edit the `<branch>` to the one they want to tract

For example you want to track the master branch, so you would do
`git ls-remote https://github.com/Henryws/conky-manager2 master | sed "s/refs\/heads\/.*//"`
If you want to track `add-1.10-support` branch you would do
`git ls-remote https://github.com/Henryws/conky-manager2 add-1.10-support | sed "s/refs\/heads\/.*//"`

**Comment by Henryws** [comment]
ah, missed that

**Comment by Henryws** [comment]
So the last thing to do is somehow make `version_gt` (version checker), to accept _all_ changes as a newer version instead of newer version = newer version

**Comment by Arsen6331** [comment]
The way PKGBUILD does `pkgver` is it's just a function that outputs whatever the new version should be and it's up to the maintainer to figure out how to do that. It does not update upon commit, it updates during install. As such, the AUR does not update `-git` packages because it does not know when a commit was made.

**Comment by Henryws** [comment]
What do you mean `It does not update upon commit, it updates during install`. That makes no sense

**Comment by Arsen6331** [comment]
`pkgver` is run during install, so the version number only updates while the package is being installed, not when the commit to the repo occurs. That way, it does not need to know when a commit occurred.

**Comment by Henryws** [comment]
Then how would it update?

**Comment by Arsen6331** [comment]
The AUR does not update `-git` packages for this reason, the user has to know there is an update and run the update on the package manually. There is also the issue that it is impossible to tell with certainty that a certain commit is newer than an older one.

**Comment by wizard-28** [comment]
> So the last thing to do is somehow make `version_gt` (version checker), to accept _all_ changes as a newer version instead of newer version = newer version, but only for `pkgver` pacscripts

When installing for the first time store the currently evaluated `pkver()` function result in `/var/log/<pkg>`' s `version` (or some other) veriable
When checking for update run the `pkgver()` function again, if the commits change store the new return value of `pkgver()` into `/var/log`'s same variable (so this time it gets changed)
Repeat the process.

So the `/var/log/` should look like this
```bash
version=<last evaluated commit hash>
description=... etc ectc
pkgver () {
 source code of the function used to evaluate newer commits from the upstream repo
}
```

I hope I could explain it better this time!

**Comment by Henryws** [comment]
No that wouldn't work well because there is no reliable way to get the contents of a function in bash

**Comment by Henryws** [comment]
What I propose is this: 
```bash
source <(curl -s "$REPO"/packages/"$i"/"$i".pacscript) && type pkgver &>/dev/null && pkgver || echo $version
```
It sources the remote file and checks for the function `pkgver`, and if it exists, run it to make the version number whatever `pkgver` outputs and if it doesn't have the `pkgver` function, echo the given version. The only thing left is to make `version_gt` think that any change in the version given by `pkgver` is a newer version

**Comment by Henryws** [comment]
Actually just found out that running `type -f function` prints out the contents of a function

**Comment by wizard-28** [comment]
Can you give a link to the repo where you are developing this feature? Then I can understand what you mean by `version_gt`

If you are developing it locally, make a `develop` branch in this repo, and upload the patches there

**Comment by Henryws** [comment]
Done
