### ISSUE TITLE
[Bug] `update.sh` is broken

### ISSUE THREAD

**Issue by wizard-28** [Henryws/pacstall#63]
**Describe the bug**

Commit [`4078d3b`](https://github.com/Henryws/pacstall/commit/4078d3b6cc90a0cb042e49b368566ba909eb66c1) broke [`update.sh`](https://github.com/Henryws/pacstall/blob/develop/misc/scripts/upgrade.sh), It didn't even pass [`CodeFactor`](http://0x0.st/-egE.png) checks, why was it merged?

**To Reproduce**

1. Run `sudo pacstall -Up`
2. See that it doesn't work and see that it returns the bash errors
3. The errors are 
```bash
/usr/share/pacstall/scripts/upgrade.sh: line 39: conditional binary operator expected
/usr/share/pacstall/scripts/upgrade.sh: line 39: syntax error near `-t'
/usr/share/pacstall/scripts/upgrade.sh: line 39: `    if [[ type -t pkgver ]]; then'
```

**Expected behavior**

No errors, and it should successfully check for updates

**Screenshots**

None

**Desktop (please complete the following information):**

- OS + version: Pop!_OS 20.04
- Pacstall Version: latest 1.2 Sangria git

**Additional context**
None

**Comment by wizard-28** [comment]
Its not fixed yet. Same error

**Comment by Henryws** [comment]
I think I got it

**Comment by Henryws** [comment]
I'm working on the output but the command technically works now

**Comment by wizard-28** [comment]
@Henryws Different error this time xD
```bash
./usr/share/pacstall/scripts/upgrade.sh: line 39: type: pkgver: not found
*/usr/share/pacstall/scripts/upgrade.sh: line 39: type: pkgver: not found
.
```

**Comment by Henryws** [comment]
Fixec

**Comment by wizard-28** [comment]
Uhh.. I think you should have made a bug fix branch, there make the possible fixes, then open a PR, like then I could test and say if the fix is working instead of commiting the possible fixes directly to the master branch which haven't been tested yet (polluting the commit history)

**Comment by Henryws** [comment]
Yeah, but I tried that (making a hotfix) and merging it to develop before pushing so it looked like I just pushed to develop

**Comment by wizard-28** [comment]
Well.. Next time lets avoid hotfixes and try to do things in feature/bug fix branches, I think the problem is fixed, I am making a PR with the new `pkgver()` function in one of my pacscripts to test the new feature
