### ISSUE TITLE
[Bug] `pkgver()` not working as intended

### ISSUE THREAD

**Issue by wizard-28** [Henryws/pacstall#64]
**Describe the bug**

`pkgver()` not working as intended, no errors but no upgrades either, I tested it after [the test PR](https://github.com/Henryws/pacstall-programs/pull/82) got merged.

**To Reproduce**

1. I have the old pre-`pkgver()` version of `bemenu-git` installed.
2. Now that I check for upgrades its saying `[+] INFO: Nothing to upgrade`

**Expected behavior**
Upgrade `bemenu-git` when checking for upgrades

**Screenshots**

None

**Desktop (please complete the following information):**

- OS + version: Pop!_OS 20.04
- Pacstall Version: 1.2.1 latest master branch

**Additional context**
None

**Comment by Henryws** [comment]
On the pkgver function, pacstall doesn't automatically set version to pkgver output. You must do something like 'version=$(stuff)'

**Comment by wizard-28** [comment]
Oh, well you could have said that earlier on the PR

**Comment by Henryws** [comment]
Or make version variable like `version=$(pkgver)

**Comment by Henryws** [comment]
I fixed it for you by making `version=$(pkgver)`

**Comment by wizard-28** [comment]
@Henryws Now its saying `./dev/fd/63: line 11: pkgver: command not found`

**Comment by wizard-28** [comment]
I think since `pkgver()` is locally sourced in `remotever`, bash is unable to access it outside of `remotever` I could be wrong though

**Comment by Henryws** [comment]
![image](https://user-images.githubusercontent.com/58742515/119344953-e54de580-bc5d-11eb-88ee-98dd8703d5bf.gif)
I'll figure it out

**Comment by Henryws** [comment]
> I think since `pkgver()` is locally sourced in `remotever`, bash is unable to access it outside of `remotever` I could be wrong though

Perhaps

**Comment by Henryws** [comment]
The problem is that `pkgver` (the function) is not being run before version wants to set it to the output

**Comment by wizard-28** [comment]
Btw echoing `remotever` gives the commit hash + 7.1.0 for some reason here is the output
```bash
[+] INFO: Checking for updates
./dev/fd/63: line 11: pkgver: command not found
O989803689130c88d6bbde4d8e889e9d81f3bdafd
o7.1.0
O
[+] INFO: Nothing to upgrade
```

**Comment by wizard-28** [comment]
Btw removing
```bash
type pkgver...
if [[ $? -eq 0]]; then
fi
``` 
and only leaving out this
```bash
    if [[ $remotever != $localver ]]; then
            echo "$i" >> /tmp/pacstall-up-list
    fi
``` 
(basically removing the parent if condition) also works

**Comment by Henryws** [comment]
So what needs to happen is for `pkgver` to not output the hash to sdtout but still get the output of it into `remotever`

**Comment by Henryws** [comment]
So redirecting the entire variable to `/dev/null` works
